name: "Secret Scan - Gitleaks"
on: [push]
jobs:
  SecretScan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
            

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Secret Scan 
        run: |
            pip install truffleHog
            trufflehog --json 


      - name: Uplaod Scan Result
        run: |
            curl -sL -O https://raw.githubusercontent.com/muralidkt/defectdojo-client/main/test/defectdojo_apiv2.py
            curl -sL -O https://raw.githubusercontent.com/muralidkt/defectdojo-client/main/test/defectdojo.py
            pip install requests
            python3 defectdojo.py --host https://defectdojo.shellctl.com --api_token 1ade1e0980c87b2cf8aa44e8ab5031c6622123c7 --engagement 19 --user admin --product_name producti-1 --file tfsec.sarif  --scanner "SARIF"
      