name: SCA Scan - Dependency Check
on: [push]
jobs:
  DependendencyScan:
    name: Dependency check
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Scan the repo
        run: | 
          curl -sL -O https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.0/dependency-check-7.0.0-release.zip
          unzip dependency-check-7.0.0-release.zip
          ./dependency-check/bin/dependency-check.sh -f JSON -s .