name: IaC Scan - Checkov  
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: IaC/
          framework: terraform 
          output_format: json 
          download_external_modules: true 
          log_level: DEBUG 
          config_file: path/this_file
          baseline: cloudformation/.checkov.baseline 
          container_user: 1000 